x-restart-policy: &restart_policy
  restart: unless-stopped
x-depends_on-healthy: &depends_on-healthy
  condition: service_healthy
x-healthcheck-defaults: &healthcheck_defaults
  # Avoid setting the interval too small, as docker uses much more CPU than one would expect.
  # Related issues:
  # https://github.com/moby/moby/issues/39102
  # https://github.com/moby/moby/issues/39388
  interval: "$HEALTHCHECK_INTERVAL"
  timeout: "$HEALTHCHECK_TIMEOUT"
  retries: $HEALTHCHECK_RETRIES
  start_period: 10s
x-coneshare-defaults: &coneshare_defaults
  <<: *restart_policy
  image: ${CONESHARE_IMAGE}
  env_file: ../app.env
  # Set the platform to build for linux/arm64 when needed on Apple silicon Macs.
  platform: ${DOCKER_PLATFORM:-}
  depends_on:
    redis:
      <<: *depends_on-healthy
    postgres:
      <<: *depends_on-healthy
  environment:
    # Leaving the value empty to just pass whatever is set
    # on the host system (or in the .env file)
    COMPOSE_PROFILES:
  volumes:
    - "../data:/data"
    - "../logs:/home/coneshare/logs"
    - "../media:/home/coneshare/app/media"

services:
  web:
    <<: *coneshare_defaults
    container_name: coneshare-web
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    healthcheck:
      <<: *healthcheck_defaults
      test:
        - "CMD"
        - "/bin/bash"
        - "-c"
        # Courtesy of https://unix.stackexchange.com/a/234089/108960
        - 'exec 3<>/dev/tcp/127.0.0.1/9998 && echo -e "GET /api/v1/_health/ HTTP/1.1\r\nhost: 127.0.0.1\r\n\r\n" >&3 && grep ok -s -m 1 <&3'
    networks:
      - coneshare-net
    ports:
      - "${CONESHARE_BIND:-80}:80/tcp"

  celery:
    <<: *coneshare_defaults
    container_name: coneshare-celery
    entrypoint: /home/coneshare/build/start-celery.sh
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "gosu", "coneshare", "python3", "-m", "celery", "-A", "backend", "inspect", "ping"]
    networks:
      - coneshare-net

  # beat:
  #   <<: *coneshare_defaults
  #   container_name: coneshare-beat
  #   command: ["beat"]
  #   ulimits:
  #     nofile:
  #       soft: 4096
  #       hard: 4096
  #   networks:
  #     - coneshare-net

  postgres:
    <<: *restart_policy
    container_name: coneshare-postgres
    image: "postgres:14-bullseye"
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
    command:
      [
        "postgres",
        "-c",
        "max_connections=${POSTGRES_MAX_CONNECTIONS:-100}",
      ]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "coneshare-postgres:/var/lib/postgresql/data"
    networks:
      - coneshare-net
      
  redis:
    <<: *restart_policy
    container_name: coneshare-redis
    image: "redis:6.2.14-alpine"
    healthcheck:
      <<: *healthcheck_defaults
      test: redis-cli ping
    volumes:
      - "coneshare-redis:/data"
    ulimits:
      nofile:
        soft: 10032
        hard: 10032
    networks:
      - coneshare-net
      
volumes:
  # These store application data that should persist across restarts.
  coneshare-postgres:
    external: true
  coneshare-redis:
    external: true
  # These store ephemeral data that needn't persist across restarts.
  # That said, volumes will be persisted across restarts until they are deleted.
  # coneshare-mq-log:

networks:
  coneshare-net:
    driver: bridge
